#监听端口
port: 8080
#服务端地址
address: 127.0.0.1:10001
#代理地址
proxy: 192.168.10.24:10001
#超时时间
timeout: 10s
#用户名(客户端)
username: admin
#密码(客户端)
password: admin
#注册事件
onRegister: |
  #username
  #password
  if username == "admin" || password == "admin" {
    throw '账号或密码错误'
  }
  return
#日志配置
log:
  level: info